"""Helpers to render BUILD files for Zig toolchain repositories."""

def render_toolchain_build(*, zig_exe, zig_version, zig_cache, translate_c):
    return """\
# Generated by zig/private/repo/toolchain_build_file.bzl

load("@rules_zig//zig:toolchain.bzl", "zig_toolchain")

zig_toolchain(
    name = "zig_toolchain_no_translate_c",
    zig_exe = {zig_exe},
    zig_h = "lib/zig.h",
    zig_lib = glob(["lib/**"]),
    zig_version = {zig_version},
    zig_cache = {zig_cache},
)

zig_toolchain(
    name = "zig_toolchain",
    zig_exe = {zig_exe},
    zig_h = "lib/zig.h",
    zig_lib = glob(["lib/**"]),
    zig_version = {zig_version},
    zig_cache = {zig_cache},
    translate_c = {translate_c},
)
""".format(
        zig_cache = repr(zig_cache),
        zig_exe = repr(zig_exe),
        zig_version = repr(zig_version),
        translate_c = translate_c and repr(str(translate_c)) or None,
    )
