"""Implementation of the zig_test rule."""

load(
    "//zig/private/common:zig_build.bzl",
    "DOCS_ATTRS",
    "TEST_ATTRS",
    "build_kind",
    "zig_build_impl",
    COMMON_ATTRS = "ATTRS",
    COMMON_TOOLCHAINS = "TOOLCHAINS",
)

DOC = """\
Builds a Zig test.

The target can be executed using `bazel test`, corresponding to `zig test`.

Documentation can be generated by requesting the `zig_docs` output group, e.g.
using the command `bazel build //my:target --output_groups=zig_docs`.

**EXAMPLE**

```bzl
load("@rules_zig//zig:defs.bzl", "zig_test")

zig_test(
    name = "my-test",
    main = "test.zig",
    srcs = [
        "utils.zig",  # to support `@import("utils.zig")`.
    ],
    deps = [
        ":my-module",  # to support `@import("my-module")`.
    ],
)
```
"""

ATTRS = COMMON_ATTRS | TEST_ATTRS | DOCS_ATTRS

TOOLCHAINS = COMMON_TOOLCHAINS

zig_test = rule(
    implementation = lambda ctx: zig_build_impl(ctx, kind = build_kind.test),
    attrs = ATTRS,
    doc = DOC,
    test = True,
    toolchains = TOOLCHAINS,
    fragments = ["cpp"],
)
