"""Implementation of the zig_shared_library rule."""

load(
    "//zig/private/common:zig_build.bzl",
    "DOCS_ATTRS",
    "SHARED_LIBRARY_ATTRS",
    "build_kind",
    "zig_build_impl",
    COMMON_ATTRS = "ATTRS",
    COMMON_TOOLCHAINS = "TOOLCHAINS",
)

DOC = """\
Builds a Zig binary.

The target can be built using `bazel build`, corresponding to `zig build-exe`,
and executed using `bazel run`, corresponding to `zig run`.

Documentation can be generated by requesting the `zig_docs` output group, e.g.
using the command `bazel build //my:target --output_groups=zig_docs`.

**EXAMPLE**

```bzl
load("@rules_zig//zig:defs.bzl", "zig_shared_library")

zig_shared_library(
    name = "my-binary",
    main = "main.zig",
    srcs = [
        "utils.zig",  # to support `@import("utils.zig")`.
    ],
    deps = [
        ":my-module",  # to support `@import("my-module")`.
    ],
)
```
"""

ATTRS = COMMON_ATTRS | SHARED_LIBRARY_ATTRS | DOCS_ATTRS

TOOLCHAINS = COMMON_TOOLCHAINS

zig_shared_library = rule(
    implementation = lambda ctx: zig_build_impl(ctx, kind = build_kind.shared_lib),
    attrs = ATTRS,
    doc = DOC,
    toolchains = TOOLCHAINS,
    fragments = ["cpp"],
)
